import type { Metadata } from "next"
import { Open_Sans } from "next/font/google"
import "./globals.css"
import { AppProviders } from "@/components/app-providers"

const openSans = Open_Sans({
  subsets: ["latin"],
  variable: "--font-open-sans",
})

export const metadata: Metadata = {
  title: {
    template: "%s | antifocus",
    default: "antifocus",
  },
  description: "Generated by create next app",
}

export const revalidate = 86400 // One day

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={openSans.className}>
        <AppProviders>{children}</AppProviders>
      </body>
    </html>
  )
}
